width: 50
height: 50
tile_size: 12
sprite_sheet: assets/textures/sprite_sheet_12.png
dirt_texture: assets/textures/dirt.png
dirt_color: [79, 49, 10]
initial_entities:
    -   {type: Grass, pos: [25, 24]}
