width: 50
height: 50
tile_size: 12
sprite_sheet: assets/textures/sprite_sheet_12.png
dirt_texture: assets/textures/dirt.png
dirt_color: [143, 97, 45]
initial_entities:
    -   {type: Rock, pos: [0, 0]}
    -   {type: Rock, pos: [0, 1]}
    -   {type: Rock, pos: [0, 2]}
    -   {type: Rock, pos: [0, 3]}
    -   {type: Rock, pos: [0, 4]}
    -   {type: Rock, pos: [0, 5]}
    -   {type: Rock, pos: [0, 6]}
    -   {type: Rock, pos: [0, 7]}
    -   {type: Rock, pos: [0, 8]}
    -   {type: Rock, pos: [0, 9]}
    -   {type: Rock, pos: [0, 10]}
    -   {type: Rock, pos: [0, 11]}
    -   {type: Rock, pos: [0, 12]}
    -   {type: Rock, pos: [0, 13]}
    -   {type: Rock, pos: [0, 14]}
    -   {type: Rock, pos: [0, 15]}
    -   {type: Rock, pos: [0, 16]}
    -   {type: Rock, pos: [0, 17]}
    -   {type: Rock, pos: [0, 18]}
    -   {type: Rock, pos: [0, 19]}
    -   {type: Rock, pos: [0, 20]}
    -   {type: Rock, pos: [0, 21]}
    -   {type: Rock, pos: [0, 22]}
    -   {type: Rock, pos: [0, 23]}
    -   {type: Rock, pos: [0, 24]}
    -   {type: Rock, pos: [0, 25]}
    -   {type: Rock, pos: [0, 26]}
    -   {type: Rock, pos: [0, 27]}
    -   {type: Rock, pos: [0, 28]}
    -   {type: Rock, pos: [0, 29]}
    -   {type: Rock, pos: [0, 30]}
    -   {type: Rock, pos: [0, 31]}
    -   {type: Rock, pos: [0, 32]}
    -   {type: Rock, pos: [0, 33]}
    -   {type: Rock, pos: [0, 34]}
    -   {type: Rock, pos: [0, 35]}
    -   {type: Rock, pos: [0, 36]}
    -   {type: Rock, pos: [0, 37]}
    -   {type: Rock, pos: [0, 38]}
    -   {type: Rock, pos: [0, 39]}
    -   {type: Rock, pos: [0, 40]}
    -   {type: Rock, pos: [0, 41]}
    -   {type: Rock, pos: [0, 42]}
    -   {type: Rock, pos: [0, 43]}
    -   {type: Rock, pos: [0, 44]}
    -   {type: Rock, pos: [0, 45]}
    -   {type: Rock, pos: [0, 46]}
    -   {type: Rock, pos: [0, 47]}
    -   {type: Rock, pos: [0, 48]}
    -   {type: Rock, pos: [0, 49]}
    -   {type: Rock, pos: [1, 0]}
    -   {type: Rock, pos: [1, 49]}
    -   {type: Rock, pos: [2, 0]}
    -   {type: Rock, pos: [2, 49]}
    -   {type: Rock, pos: [3, 0]}
    -   {type: Rock, pos: [3, 49]}
    -   {type: Rock, pos: [4, 0]}
    -   {type: Rock, pos: [4, 49]}
    -   {type: Rock, pos: [5, 0]}
    -   {type: Rock, pos: [5, 49]}
    -   {type: Rock, pos: [6, 0]}
    -   {type: Rock, pos: [6, 49]}
    -   {type: Rock, pos: [7, 0]}
    -   {type: Rock, pos: [7, 49]}
    -   {type: Rock, pos: [8, 0]}
    -   {type: Rock, pos: [8, 49]}
    -   {type: Rock, pos: [9, 0]}
    -   {type: Rock, pos: [9, 49]}
    -   {type: Rock, pos: [10, 0]}
    -   {type: Rock, pos: [10, 49]}
    -   {type: Rock, pos: [11, 0]}
    -   {type: Rock, pos: [11, 49]}
    -   {type: Rock, pos: [12, 0]}
    -   {type: Rock, pos: [12, 49]}
    -   {type: Rock, pos: [13, 0]}
    -   {type: Rock, pos: [13, 49]}
    -   {type: Rock, pos: [14, 0]}
    -   {type: Rock, pos: [14, 49]}
    -   {type: Rock, pos: [15, 0]}
    -   {type: Rock, pos: [15, 49]}
    -   {type: Rock, pos: [16, 0]}
    -   {type: Rock, pos: [16, 49]}
    -   {type: Rock, pos: [17, 0]}
    -   {type: Rock, pos: [17, 49]}
    -   {type: Rock, pos: [18, 0]}
    -   {type: Rock, pos: [18, 49]}
    -   {type: Rock, pos: [19, 0]}
    -   {type: Rock, pos: [19, 49]}
    -   {type: Rock, pos: [20, 0]}
    -   {type: Rock, pos: [20, 49]}
    -   {type: Rock, pos: [21, 0]}
    -   {type: Rock, pos: [21, 49]}
    -   {type: Rock, pos: [22, 0]}
    -   {type: Rock, pos: [22, 49]}
    -   {type: Rock, pos: [23, 0]}
    -   {type: Rock, pos: [23, 49]}
    -   {type: Rock, pos: [24, 0]}
    -   {type: Rock, pos: [24, 49]}
    -   {type: Rock, pos: [25, 0]}
    -   {type: Grass, pos: [25, 24]}
    -   {type: Rock, pos: [25, 49]}
    -   {type: Rock, pos: [26, 0]}
    -   {type: Rock, pos: [26, 49]}
    -   {type: Rock, pos: [27, 0]}
    -   {type: Rock, pos: [27, 49]}
    -   {type: Rock, pos: [28, 0]}
    -   {type: Rock, pos: [28, 49]}
    -   {type: Rock, pos: [29, 0]}
    -   {type: Rock, pos: [29, 49]}
    -   {type: Rock, pos: [30, 0]}
    -   {type: Rock, pos: [30, 49]}
    -   {type: Rock, pos: [31, 0]}
    -   {type: Rock, pos: [31, 49]}
    -   {type: Rock, pos: [32, 0]}
    -   {type: Rock, pos: [32, 49]}
    -   {type: Rock, pos: [33, 0]}
    -   {type: Rock, pos: [33, 49]}
    -   {type: Rock, pos: [34, 0]}
    -   {type: Rock, pos: [34, 49]}
    -   {type: Rock, pos: [35, 0]}
    -   {type: Rock, pos: [35, 49]}
    -   {type: Rock, pos: [36, 0]}
    -   {type: Rock, pos: [36, 49]}
    -   {type: Rock, pos: [37, 0]}
    -   {type: Rock, pos: [37, 49]}
    -   {type: Rock, pos: [38, 0]}
    -   {type: Rock, pos: [38, 49]}
    -   {type: Rock, pos: [39, 0]}
    -   {type: Rock, pos: [39, 49]}
    -   {type: Rock, pos: [40, 0]}
    -   {type: Rock, pos: [40, 49]}
    -   {type: Rock, pos: [41, 0]}
    -   {type: Rock, pos: [41, 49]}
    -   {type: Rock, pos: [42, 0]}
    -   {type: Rock, pos: [42, 49]}
    -   {type: Rock, pos: [43, 0]}
    -   {type: Rock, pos: [43, 49]}
    -   {type: Rock, pos: [44, 0]}
    -   {type: Rock, pos: [44, 49]}
    -   {type: Rock, pos: [45, 0]}
    -   {type: Rock, pos: [45, 49]}
    -   {type: Rock, pos: [46, 0]}
    -   {type: Rock, pos: [46, 49]}
    -   {type: Rock, pos: [47, 0]}
    -   {type: Rock, pos: [47, 49]}
    -   {type: Rock, pos: [48, 0]}
    -   {type: Rock, pos: [48, 49]}
    -   {type: Rock, pos: [49, 0]}
    -   {type: Rock, pos: [49, 1]}
    -   {type: Rock, pos: [49, 2]}
    -   {type: Rock, pos: [49, 3]}
    -   {type: Rock, pos: [49, 4]}
    -   {type: Rock, pos: [49, 5]}
    -   {type: Rock, pos: [49, 6]}
    -   {type: Rock, pos: [49, 7]}
    -   {type: Rock, pos: [49, 8]}
    -   {type: Rock, pos: [49, 9]}
    -   {type: Rock, pos: [49, 10]}
    -   {type: Rock, pos: [49, 11]}
    -   {type: Rock, pos: [49, 12]}
    -   {type: Rock, pos: [49, 13]}
    -   {type: Rock, pos: [49, 14]}
    -   {type: Rock, pos: [49, 15]}
    -   {type: Rock, pos: [49, 16]}
    -   {type: Rock, pos: [49, 17]}
    -   {type: Rock, pos: [49, 18]}
    -   {type: Rock, pos: [49, 19]}
    -   {type: Rock, pos: [49, 20]}
    -   {type: Rock, pos: [49, 21]}
    -   {type: Rock, pos: [49, 22]}
    -   {type: Rock, pos: [49, 23]}
    -   {type: Rock, pos: [49, 24]}
    -   {type: Rock, pos: [49, 25]}
    -   {type: Rock, pos: [49, 26]}
    -   {type: Rock, pos: [49, 27]}
    -   {type: Rock, pos: [49, 28]}
    -   {type: Rock, pos: [49, 29]}
    -   {type: Rock, pos: [49, 30]}
    -   {type: Rock, pos: [49, 31]}
    -   {type: Rock, pos: [49, 32]}
    -   {type: Rock, pos: [49, 33]}
    -   {type: Rock, pos: [49, 34]}
    -   {type: Rock, pos: [49, 35]}
    -   {type: Rock, pos: [49, 36]}
    -   {type: Rock, pos: [49, 37]}
    -   {type: Rock, pos: [49, 38]}
    -   {type: Rock, pos: [49, 39]}
    -   {type: Rock, pos: [49, 40]}
    -   {type: Rock, pos: [49, 41]}
    -   {type: Rock, pos: [49, 42]}
    -   {type: Rock, pos: [49, 43]}
    -   {type: Rock, pos: [49, 44]}
    -   {type: Rock, pos: [49, 45]}
    -   {type: Rock, pos: [49, 46]}
    -   {type: Rock, pos: [49, 47]}
    -   {type: Rock, pos: [49, 48]}
    -   {type: Rock, pos: [49, 49]}
